### ISSUE TITLE
Feature: Hide caret when command input loses focus

### ISSUE THREAD

**Issue by rafi** [lambdalisue/neovim-prompt#2]
I'm using Shougo's [denite.nvim](https://github.com/Shougo/denite.nvim) which uses your library, and would like to find a way to hide the caret while in _denite's_ normal-mode.

For example this screenshot shows normal-mode and a selected file, `LICENSE`, in the other buffer:
![image](https://cloud.githubusercontent.com/assets/147918/20238212/da5a2a1c-a8ee-11e6-82eb-0e3f0ca045bb.png)

Is it possible to hide the caret somehow?

**Comment by lambdalisue** [comment]
1. neovim-prompt has partially imported in denite.nvim but haven't complete yet. The caret feature is currently denite.nvim's responsibility
2. As long as I know, the caret cannot be removed in Python's mainloop while neovim-prompt/denite.nvim use `getchar()` feature of Neovim/Vim. The "normal" mode is actually in Python's loop so I don't think it is possible (let me know if you find any way).

**Comment by rafi** [comment]
Thank you for the information.
Maybe `curses` is where I should look...
