### ISSUE TITLE
normal vim text object actions don't work in neovim-prompt

### ISSUE THREAD

**Issue by sodiumjoe** [lambdalisue/neovim-prompt#8]
I'm trying to move from `unite` to `denite`. I don't really know anything about the implementation of either, but in unite, all the normal vim text interactions would work, for example, from normal mode`cc` to clear the line, and enter insert mode, `cw` to delete to end of word and enter insert mode, etc.

Other differences like it seems like `esc` should always go to normal mode, but it quits the prompt when in insert mode and enters insert mode from normal mode.

I would think most vim users would have the same expectations in the prompt.

I even tried implementing my most common used subset with mappings, but because of #7  it doesn't look like this is possible (for example `cc` would be `<denite:delete_entire_text>` then `<denite:enter_mode:normal>`.

Do you have any guidance or suggestions?

**Comment by lambdalisue** [comment]
> I'm trying to move from unite to denite. I don't really know anything about the implementation of either, but in unite, all the normal vim text interactions would work, for example, from normal modecc to clear the line, and enter insert mode, cw to delete to end of word and enter insert mode, etc.

This is a prompt and not a buffer. I mean, `cc` or `cw` won't work on Vim's builtin prompt as well (hit `:` on your Vim then you will see what I mean 👍 )

> Other differences like it seems like esc should always go to normal mode, but it quits the prompt when in insert mode and enters insert mode from normal mode.

This is a denite.nvim's part. You should discuss with @Shougo but I think you have to understand the difference of unite/denite. denite is NOT a complete replacement of unite. The interface is quite difference (unite is a buffer based, denite is a prompt based) and you have to get used to.

> I even tried implementing my most common used subset with mappings, but because of #7 it doesn't look like this is possible (for example cc would be <denite:delete_entire_text> then <denite:enter_mode:normal>.

That is the issue of this plugin but as #7 said, it is quite difficult to support.
If you desire, you can add custom actions by writing python but I really think your use-case is not denite-like.

**Comment by sodiumjoe** [comment]
Thanks again for the quick response!

> This is a prompt and not a buffer.

That's an interesting distinction that did not occur to me, but now that you put it that way, I think what I like about `unite` is exactly that it's a buffer and behaves like any other vim buffer, giving me the full power of vim. I often use `<C-f>` from the vim prompt to get this behavior as well.

I understand if that's not your intent or philosophy with this project, so I'll have to think about the tradeoffs while considering switching to denite. (I can't help but note that `neovim-prompt` does have *some* buffer-like abilities, though like insert/normal mode 😛 .)

**Comment by lambdalisue** [comment]
> I can't help but note that neovim-prompt does have some buffer-like abilities, though like insert/normal mode 

Actually, that is denite.nvim's feature. What neovim-prompt provide is a just action mapping and denite.nvim use that feature to mimic insert/normal or any user custom modes 👍

**Comment by sodiumjoe** [comment]
Ah I see, then maybe Shougo thinks of denite as somewhat buffer-like then... at least I hope so!
